Avg & Max response summary
pinpoint-apm/pinpoint pull request #7554
Opened 2021-01-17 13:11 UTC by yjqg6666

A new PR which is rebased on the current master. The old PR is #7115.

2021-01-18 03:02 UTC, binDongKim commented
Is there anything you have changed in UI side since the last review?

2021-01-18 05:18 UTC, yjqg6666 commented
> Is there anything you have changed in UI side since the last review?

Nothing changed, just git-rebased on the current master.

2021-01-19 06:22 UTC, emeroad commented
![image](https://user-images.githubusercontent.com/7564547/104995582-e251a700-5a69-11eb-804a-f3372aa7c4e6.png)

@yjqg6666
Thanks for your contribution
The avg/max values ​​are not displayed in the servermap
Please review this PR

2021-01-19 06:30 UTC, yjqg6666 commented
The PRed version will not show avg/max info on the edges of the servermap, only on the dedicated chart.

2021-01-19 06:33 UTC, yjqg6666 commented
Do you mean the ServerMap illustrated in #7212?

2021-01-19 06:40 UTC, yjqg6666 commented
If so and this feature is needed, i will append the related commits ASAP.

2021-01-19 09:12 UTC, emeroad commented
Okay. This feature will be merged in 2.3.0

2021-01-19 10:09 UTC, yjqg6666 commented
@binDongKim @emeroad Just added the feature in the commit 7a2897f2f59c27c6147e180862453c23fd10383a. Please take a look.

2021-01-21 05:41 UTC, binDongKim requested changes
I've left a simple comment. Thanks for your contribution.

2021-01-21 05:41 UTC, binDongKim commented on web/src/main/angular/src/app/core/components/server-map/class/server-map-diagram-with-cytoscapejs.class.ts
> +
- Please use single quotes for string for the consistency.
- Give a space before `0` in line 161.

2021-01-21 06:04 UTC, binDongKim approved these changes

2021-02-08 01:14 UTC, merged