[#8133] show Avg&Max Response summary info on ServerMap edge
pinpoint-apm/pinpoint pull request #8135
Opened 2021-08-19 10:00 UTC by yjqg6666

Resolve #8133.

# Feature
![image](https://user-images.githubusercontent.com/1879641/130049527-5c2caf31-2b93-4fce-aaaa-0c3f1d89cdb9.png)

2021-08-20 06:31 UTC, binDongKim commented
We have talked through this feature and it seems like a decent one but at the same time, if the server-map is complicated, things would become harder to recognize with this look. So I guess we will need a better but simpler way to display the info such as popping-up a small info-box when hovering the mouse on the link. 

Thank you.

2021-08-20 06:48 UTC, yjqg6666 commented
On the right sidebar, there is already avg&max chart which is shown only when clicking on edges. Popping-up is still indirect and unnecessary. How about showing different line thickness and/or color regarding avg&max value range?

2021-08-20 08:28 UTC, binDongKim commented
That could work but just wondering how it would look like with that approach.
Would you try implementing it with a middle-big size server-map and share it here if it doesn't look confusing?

2021-08-20 09:38 UTC, emeroad commented
@yjqg6666 
Can you remove MAX and put only AVG?
It would be nice to see something like UserLink `1 (9006)`

Data Format
1. 9999 (100)
2. 9999 / 100

Would 1 be better?

2021-08-20 09:54 UTC, emeroad commented
In my opinion, it would be better to add TimeUnit to AVG

100  -> 100 ms
6000 -> 1.0 sec
6100 -> 1.1 sec
61000 -> 6.1 min

There may be a way to omit precision.
6002 -> 1.0 sec

2021-08-24 09:02 UTC, yjqg6666 commented
Update:

In the main server map:
![image](https://user-images.githubusercontent.com/1879641/130588611-36b78cb6-ad0f-4766-b2b8-8ce8c032e38b.png)
In the transaction server map:
![image](https://user-images.githubusercontent.com/1879641/130588865-5f07cbd8-1ea0-4ae0-b4fa-95560763ed5f.png)

2021-08-25 02:45 UTC, binDongKim requested changes
I've left a few comments mostly about the syntax. 

Check them out and after you change them, please rebase(squash) all the commits into one.

Thank you.

2021-08-25 02:45 UTC, binDongKim commented on web/src/main/angular/src/app/core/components/server-map/class/server-map-diagram-with-cytoscapejs.class.ts
> +                                label: totalCount.toLocaleString() + responseInfo,
Use template literals when concatenating strings.
```suggestion
                                label: `${totalCount.toLocaleString()}${responseInfo}`,
```

2021-08-25 02:45 UTC, binDongKim commented on web/src/main/angular/src/app/core/components/server-map/class/server-map-diagram-with-cytoscapejs.class.ts
> -                        label: totalCount.toLocaleString(),
Same as above

2021-08-25 02:45 UTC, binDongKim commented on web/src/main/angular/src/app/core/components/server-map/class/server-map-diagram-with-cytoscapejs.class.ts
> +
1. Add line-break after `if` statement and variable declaration.
2. Use template literals when concatenating strings.
3. Use conditional ternary operator to make the code concise.

```suggestion
    getResponseInfo(linkData: ILinkInfo|any): any {
        if (typeof linkData === 'undefined' || !linkData) {
            return '';
        }

        const histogramAvg = linkData.responseStatistics ? linkData.responseStatistics.Avg : 0;

        return histogramAvg > 0 ? ` (${this.formatTime(histogramAvg)})` : '';
    }

    private formatTime(val: number): string {
        return val < 1000 ? `${val} ms`
            : val % 60000 === 0 ? `${(val / 60000)} min`
            : `${(val / 1000.0).toFixed(2).replace('.00', '').replace(/(\.\d)0$/, '$1')} sec`;
    }
```

2021-08-25 06:42 UTC, yjqg6666 commented
@binDongKim Squashed and rebased.

2021-08-25 06:58 UTC, merged