[#8162] cache applications api on browser/server side
pinpoint-apm/pinpoint pull request #8163
Opened 2021-08-27 11:06 UTC by yjqg6666

Resolve #8162 

# Feature
By default, the application list would be cached by Ehcache for 120 seconds(configured in ehcache.xml) and be cached by browser  for 60 seconds (configured by web.applicationList.cacheTime in pinpoint-web-root.properties). If the request having no "If-Non-Match" header(when it's the first time to request or after expired browser cache time), ehcache would be evicted and retrieve data from hbase. The cache can also be clear by requesting {web_host}/applications.pinpoint?clearCache manually.
**The first time to request for a user, there would be no cache in use.**

You may let the web browser cache for a longer time by setting `-Dweb.applicationList.cacheTime` to a bigger value (in seconds). The following request would get "304 Not Modified response header" and no response body. The browser would use previously cached data.

![image](https://user-images.githubusercontent.com/1879641/131119178-57c25cc8-9374-444e-99cc-f1b93456b412.png)

In the above picture:
1. no cache on the browser & server sides.
2. cache on the browser side.
3. cache on the server side only and no application list data to transfer.

# Verification
```
# request for the first time or with expired cache
$ curl 'http://localhost:8080/applications.pinpoint' -D-   

# request with eTag returned by the previous response eTag header value
$ curl 'http://localhost:8080/applications.pinpoint' -D- -H 'If-None-Match: "applicationNameListVer1"'  

# clear server cached list
$ curl 'http://localhost:8080/applications.pinpoint?clearCache' -D-

```

2021-09-01 14:11 UTC, emeroad commented on web/src/main/java/com/navercorp/pinpoint/web/controller/MainController.java
>      }
@yjqg6666 
In case of `noUpdate`, it seems that NOT_MODIFIED(304) should be set in HttpStatus.
```java
        if (noUpdate) {
            final ResponseEntity.BodyBuilder builder = ResponseEntity.status(HttpStatus.NOT_MODIFIED).eTag(newETag);
            return builder.build();
        } else {
            ResponseEntity.BodyBuilder builder = ResponseEntity.ok().eTag(newETag);
            return builder.body(new ApplicationGroup(applicationList));
        }
```

2021-09-02 01:46 UTC, yjqg6666 commented on web/src/main/java/com/navercorp/pinpoint/web/controller/MainController.java
>      }
I tested and got status code 304, so no status code set explicitly then. I will add it soon.

2021-09-02 10:43 UTC, emeroad commented
How about changing the applicationList's reload button click action?
- Bypass browser cache and force update applicationlist for data freshness

eg)
1. Add magic key to /applications.list
2. Add clearCache parameter to applications.list

/applications.list?clearCache&magic=1234

2021-09-03 01:57 UTC, yjqg6666 commented
@emeroad  great idea.

2021-09-03 03:03 UTC, yjqg6666 commented
@emeroad implemented.

![image](https://user-images.githubusercontent.com/1879641/131944392-58f92985-f073-485e-9581-3e07f2f2ad3e.png)

2021-09-03 05:45 UTC, binDongKim commented
@yjqg6666 
When I click the reload button, it passes the parameters which I guess is for bypassing the cache and update the data but I noticed the browser keeps fetching the data from the cache even when clicking the button in short period.

![스크린샷 2021-09-03 오후 2 43 38](https://user-images.githubusercontent.com/8830238/131956225-5c23b559-5178-408c-940f-91740698ffb8.png)

Is this an expected behavior?

2021-09-03 06:00 UTC, yjqg6666 commented
@binDongKim It's not and a new commit is appended to fix it.

2021-09-03 06:39 UTC, binDongKim requested changes
Other than the simple line-break comment, everything seems to work well.

After you change it, please rebase and squash `c00443d75186be4487d62a770c14e8753cfd2bc6`,
`9152148ad83f03929a39045d984aca207cf7a091` commits into one commit.

2021-09-03 06:39 UTC, binDongKim commented on web/src/main/angular/src/app/core/components/application-list/application-list-data.service.ts
> +        return this.http.get<IApplication[]>(this.url, options).pipe(
```suggestion
        const options = force ? {params: {clearCache:'true', from: 'reload', _t: Date.now().toString()}} : {};
        
        return this.http.get<IApplication[]>(this.url, options).pipe(
```
Please add a line-break after declaration.

2021-09-03 06:46 UTC, yjqg6666 commented
@binDongKim Done and thanks for the guide and review.

2021-09-03 06:53 UTC, binDongKim commented
@yjqg6666 
Things look good to go in frong-end side. Thank you!

2021-09-03 06:58 UTC, binDongKim approved these changes

2021-09-03 07:27 UTC, emeroad approved these changes

2021-09-03 07:27 UTC, merged