[#8480] add global navigation side bar
pinpoint-apm/pinpoint pull request #8481
Opened 2021-12-09 04:54 UTC by BillionaireDY

@binDongKim

2021-12-13 06:23 UTC, binDongKim requested changes

2021-12-13 06:23 UTC, binDongKim commented on web/src/main/angular/src/app/core/components/side-navigation-bar/side-navigation-bar-container.component.ts
> +import { takeUntil } from 'rxjs/operators';
```suggestion
import { Component, OnInit, ChangeDetectionStrategy, ChangeDetectorRef, OnDestroy } from '@angular/core';
import { Router } from '@angular/router';
import { Subject } from 'rxjs';
import { takeUntil } from 'rxjs/operators';

import { UrlPathId } from 'app/shared/models';
import { WebAppSettingDataService, NewUrlStateNotificationService, StoreHelperService, TRACKED_EVENT_LIST, UrlRouteManagerService, WindowRefService, AnalyticsService } from 'app/shared/services';
import { Actions } from 'app/shared/store/reducers';
```

Locate the external import statement at the top and the others after them(with a blank line)

2021-12-13 06:23 UTC, binDongKim commented on web/src/main/angular/src/app/core/components/side-navigation-bar/side-navigation-bar-container.component.ts
> +}
```suggestion
interface ISNBMeta {
    topItems: ISNBItem[];
    bottomItems: ISNBItem[];
}
```

Correct the interface syntax

2021-12-13 06:23 UTC, binDongKim commented on web/src/main/angular/src/app/core/components/configuration-experimental/configuration-experimental-container.component.ts
> +                window.location.reload();
```suggestion
this.urlRouteManagerService.reload();
```
Use `UrlRouteManagerService` reload method: `this.urlRouteManagerService.reload();`

2021-12-13 06:23 UTC, binDongKim commented on web/src/main/angular/src/app/core/components/side-navigation-bar/side-navigation-bar-container.component.ts
> +    minimize: boolean = false;
```suggestion
    minimize = false;
```
Delete the type annotation per lint

2021-12-13 06:23 UTC, binDongKim commented on web/src/main/angular/src/app/core/components/side-navigation-bar/side-navigation-bar-container.component.ts
> +        this.minimize = this.webAppSettingDataService.getSideNavBarScale();
Initialize variables in `ngOnInit()`. There shouldn't be any initialization in constructor unless it's necessary.

2021-12-13 06:23 UTC, binDongKim commented on web/src/main/angular/src/app/core/components/side-navigation-bar/side-navigation-item.component.ts
> +import { Component, OnInit, Input, Output, EventEmitter, SimpleChanges, ViewChild, ViewChildren, QueryList, ElementRef, OnChanges, AfterViewInit } from '@angular/core';
Add a line-break after the external import statement

2021-12-13 06:23 UTC, binDongKim commented on web/src/main/angular/src/app/core/components/side-navigation-bar/side-navigation-item.component.ts
> +    }
Remove unused lifecycle hook

2021-12-13 06:23 UTC, binDongKim commented on web/src/main/angular/src/app/routes/filtered-map-page/filtered-map-page.component.ts
>  import { Component, OnInit, ChangeDetectionStrategy } from '@angular/core';
Add a line-break after the external import statement

2021-12-14 03:01 UTC, binDongKim requested changes

2021-12-14 03:01 UTC, binDongKim commented on web/src/main/angular/src/app/core/components/side-navigation-bar/side-navigation-bar-container.component.ts
> +}
```suggestion
interface ISNBMeta {
    topItems: ISNBItem[];
    bottomItems: ISNBItem[];
}
```

Correct the interface syntax

2021-12-14 03:01 UTC, binDongKim commented on web/src/main/angular/src/app/core/components/side-navigation-bar/side-navigation-item.component.ts
> +    }
Remove if it's unnecessary

2021-12-14 05:22 UTC, BillionaireDY commented on web/src/main/angular/src/app/core/components/side-navigation-bar/side-navigation-item.component.ts
> +    }
This is necessary to calculate the height when SNB scale changes.

2022-01-03 06:45 UTC, merged