[#9631] Record SpanEventException in SpanRecorder.recordException()
pinpoint-apm/pinpoint pull request #9632
Opened 2023-01-12 10:24 UTC by intr3p1d

grpc-idl: https://github.com/pinpoint-apm/pinpoint-grpc-idl/pull/14

Their can be an Exception in a `SpanEvent`. (`Span` or `SpanChunk` can have multiple Exception)
`ExceptionRecordingService` reduces redunduncy.

2023-01-18 02:44 UTC, ga-ram approved these changes

2023-01-20 08:50 UTC, smilu97 requested changes

2023-01-20 08:50 UTC, smilu97 commented on profiler/src/main/java/com/navercorp/pinpoint/profiler/context/exception/DefaultExceptionRecordingService.java
> +public class DefaultExceptionRecordingService implements ExceptionRecordingService {
Service라는 이름에서 이것이 Stateless하다는 인상을 조금 받게 되는데 실제로는 그렇지가 않네요. `previous`, `startTime`을 묶어서 어떠한 Context로 따로 정의하고 외부에서 주입 받을 수 있을 것 같습니다. 이렇게 되면 `isTopLevelException` 같은 메소드들도 해당 Context의 메소드로 따로 뺼 수 있을 것 같습니다.

2023-01-20 08:50 UTC, smilu97 commented on profiler/src/main/java/com/navercorp/pinpoint/profiler/context/recorder/DefaultRecorderFactory.java
> +        final ExceptionRecordingService exceptionRecordingService = new BypassExceptionRecordingService();
@emeroad SpanRecordContext 같은 것이 필요하지 않을까 싶은데 어떨까요?

2023-01-25 01:23 UTC, donghun-cho approved these changes

2023-01-31 08:48 UTC, smilu97 approved these changes

2023-07-24 06:50 UTC, merged